/**
 * File generated by Magnet rest2mobile 1.1 - Jul 31, 2015 3:08:28 PM
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.paradise.api.model;


import org.parceler.Parcel;

/**
 * Generated from json example
{
  "intro" : {
    "can" : false,
    "has" : false
  }
}

 */

@Parcel
public class Abilities {

  private Intro intro;

  public Intro getIntro() {
    return intro;
  }

}
