/**
 * File generated by Magnet rest2mobile 1.1 - Jul 31, 2015 3:08:28 PM
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.paradise.api.model;


import org.parceler.Parcel;

/**
 * Generated from json example
{
  "id" : 1664,
  "tag_type" : "LocationTag",
  "name" : "newyork,ny",
  "display_name" : "NewYorkCity",
  "angellist_url" : "https://angel.co/new-york-ny-1"
}

 */

@Parcel
public class Location {

  
  private String angellist_url;

  
  private String display_name;

  
  private Integer id;

  
  private String name;

  
  private String tag_type;

  public String getAngellist_url() {
    return angellist_url;
  }
  public String getDisplay_name() {
    return display_name;
  }
  public Integer getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public String getTag_type() {
    return tag_type;
  }

}
