/**
 * File generated by Magnet rest2mobile 1.1 - Aug 16, 2015 6:48:08 PM
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.paradise.api.model;

import com.google.gson.annotations.SerializedName;

import org.parceler.Parcel;

import java.util.List;

/**
 * Generated from json example
{
  "name" : "JordanFliegel",
  "id" : 61616,
  "bio" : "Founder@coachup.Investorin30+startups@bridgeBoys.Advisor@FortifiedBicycle.Mentor@techstars&@masschallenge.",
  "follower_count" : 716,
  "angellist_url" : "https://angel.co/jfleeg",
  "image" : "https://d1qb2nb5cznatu.cloudfront.net/users/61616-medium_jpg?1435352069",
  "blog_url" : "",
  "online_bio_url" : "http://www.coachup.com",
  "twitter_url" : "http://twitter.com/#!/jfleeg",
  "facebook_url" : "",
  "linkedin_url" : "http://www.linkedin.com/profile/edit?trk=hb_tab_pro_top",
  "aboutme_url" : "http://about.me/jordanfliegel",
  "github_url" : "",
  "dribbble_url" : "",
  "behance_url" : "",
  "resume_url" : "http://something.com",
  "what_ive_built" : "",
  "what_i_do" : "Bymakinghelpfulintroductions.AsanentrepreneurinBoston,andasaninvestorinover30startups,Iamfortunatetoknowincredibleentrepreneurs,mentors,investors,andserviceproviders.",
  "criteria" : "Exceptionalpeoplewhoarepassionateaboutchangingtheworld.",
     ...

 */

@Parcel
public class Person  {

  public String getFirtLocationName(){

    if (locations !=null && locations.size() > 0) {

      return locations.get(0).getDisplay_name();
    }

    return "";
  }

  public String getFirstRoleTag(){

    if (roleTags !=null && roleTags.size() > 0) {

      return roleTags.get(0).getDisplay_name();
    }

    return "";
  }

  
  private String aboutme_url;

  
  private String angellist_url;

  
  private String behance_url;

  
  private String bio;

  
  private String blog_url;

  
  private String criteria;

  
  private String dribbble_url;

  
  private String facebook_url;

  
  private Integer follower_count;

  
  private String github_url;

  
  private Integer id;

  
  private String image;

  
  private Boolean investor;

  
  private String linkedin_url;

  
  private List<Location> locations;

  
  private String name;

  
  private String online_bio_url;

  
  private String resume_url;


  @SerializedName("roles")
  private List<RoleTag> roleTags;

  
  private List<SkillTag> skillTags;

  
  private String twitter_url;

  
  private String what_i_do;

  
  private String what_ive_built;

  public String getAboutme_url() {
    return aboutme_url;
  }
  public String getAngellist_url() {
    return angellist_url;
  }
  public String getBehance_url() {
    return behance_url;
  }
  public String getBio() {
    return bio;
  }
  public String getBlog_url() {
    return blog_url;
  }
  public String getCriteria() {
    return criteria;
  }
  public String getDribbble_url() {
    return dribbble_url;
  }
  public String getFacebook_url() {
    return facebook_url;
  }
  public Integer getFollower_count() {
    return follower_count;
  }
  public String getGithub_url() {
    return github_url;
  }
  public Integer getId() {
    return id;
  }
  public String getImage() {
    return image;
  }
  public Boolean getInvestor() {
    return investor;
  }
  public String getLinkedin_url() {
    return linkedin_url;
  }
  public List<Location> getLocations() {
    return locations;
  }
  public String getName() {
    return name;
  }
  public String getOnline_bio_url() {
    return online_bio_url;
  }
  public String getResume_url() {
    return resume_url;
  }
  public List<RoleTag> getRoleTags() {
    return roleTags;
  }
  public List<SkillTag> getSkillTags() {
    return skillTags;
  }
  public String getTwitter_url() {
    return twitter_url;
  }
  public String getWhat_i_do() {
    return what_i_do;
  }
  public String getWhat_ive_built() {
    return what_ive_built;
  }


}
