/**
 * File generated by Magnet rest2mobile 1.1 - Jul 31, 2015 3:08:28 PM
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.paradise.api.model;


import android.os.Parcelable;

/**
 * Generated from json example
{
  "thumb" : "https://d2gn4xht817m0g.cloudfront.net/p/product_screenshots/images/thumb/000/547/146/547146-5b7ba5a97d3a53c35e2c9f405e82b69b5dcff6d3.jpg?1435344957",
  "original" : "https://d2gn4xht817m0g.cloudfront.net/p/product_screenshots/images/original/000/547/146/547146-4fc8703b2c8f277c5d801a86fe1e4fbc472282f3.png?1435344957"
}

 */

public class Screenshot implements Parcelable {

  private String original;
  
  private String thumb;

  public String getOriginal() {
    return original;
  }
  public String getThumb() {
    return thumb;
  }


  @Override
  public int describeContents() {

    return 0;
  }

  @Override
  public void writeToParcel(android.os.Parcel dest, int flags) {

    dest.writeString(this.original);
    dest.writeString(this.thumb);
  }

  public Screenshot() {

  }

  protected Screenshot(android.os.Parcel in) {

    this.original = in.readString();
    this.thumb = in.readString();
  }

  public static final Parcelable.Creator<Screenshot> CREATOR = new Parcelable.Creator<Screenshot>() {

    public Screenshot createFromParcel(android.os.Parcel source) {

      return new Screenshot(source);
    }

    public Screenshot[] newArray(int size) {

      return new Screenshot[size];
    }
  };
}
